# Generated by Django 5.1.1 on 2024-10-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_user_icono'),
        ('posts', '0003_comentario_delete_comentarios'),
    ]

    operations = [
    ]
