# Generated by Django 5.1.1 on 2024-10-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_merge_20241018_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='media/usuarios'),
        ),
    ]
