# Generated by Django 5.1.1 on 2024-10-01 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_texto_post_contenido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publicado',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='Categorias',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
